apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  config.yaml: |
    server:
      host: "0.0.0.0"
      port: 8080
      window_size: 5
    paths:
      media: "./media"
      ads: "./ads"
      manifests: "./manifests"
    ads:
      - id: "adv1"
        duration: 30 